import {loadTimeData} from './resources/js/load_time_data.js';
loadTimeData.data = {
    "actionBack": "Back to menu",
    "actionCancel": "Cancel",
    "actionClose": "Close",
    "actionNext": "Next",
    "actionPause": "Pause",
    "actionPlay": "Play",
    "actionPrev": "Previous",
    "actionSave": "Save changes",
    "code": "Cheat code activated!",
    "codeCheat": "Cheat code activated! $1",
    "codeScoring": "Scoring turned off for this round.",
    "editPlayerBody": "Edit Body",
    "editPlayerColor": "Color",
    "editPlayerExtras": "Edit Accessories",
    "editPlayerHair": "Edit Hairstyle",
    "editPlayerOutfit": "Edit Outfit",
    "fontfamily": "system-ui, sans-serif",
    "fontfamilyMd": "system-ui, sans-serif",
    "fontsize": "75%",
    "gameEditPlayer": "Edit player",
    "gameEditTheme": "Edit theme",
    "gameSettings": "Settings",
    "gameShare": "Share",
    "genericEvent": "Special event",
    "genericMode": "New mode",
    "genericSeasonal": "Seasonal",
    "genericTheme": "New theme",
    "is_windows_xbox_sku": "false",
    "language": "en",
    "menuMainButton": "Start game",
    "menuOverButton": "New game",
    "menuOverTitle": "Game over",
    "menuOverTitleAlt": "So close!",
    "menuOverTitleHighScore": "High score!",
    "menuPauseButton": "Resume game",
    "menuPauseTitle": "Paused",
    "modeCollectorHowToPlay": "Collect all the coins",
    "modeCollectorTitle": "Collector",
    "modeEndlessHowToPlay": "Travel as far as you can",
    "modeEndlessTitle": "Endless",
    "modeTimetrialHowToPlay": "Rush to the finish line",
    "modeTimetrialTitle": "Time trial",
    "modeZigzagHowToPlay": "Pass through every gate",
    "modeZigzagTitle": "Zig zag",
    "newHighScore": "New high score!",
    "old_buoy_high_score": 13,
    "old_classic_high_score": 13523,
    "old_speed_high_score": 45904,
    "settingsCredits": "Game credits",
    "settingsCreditsDesign": "Design team:",
    "settingsCreditsEngineering": "Engineering team:",
    "settingsHighVisiblityToggle": "High visiblity",
    "settingsOff": "Off",
    "settingsOn": "On",
    "settingsReducedMotionToggle": "Reduced motion",
    "settingsReducedSpeedToggle": "Reduced speed",
    "settingsResetAllStats": "Reset all stats",
    "settingsResetAllStatsDialogText": "Are you sure you want to reset all your game stats, including your high scores?",
    "settingsResetAllStatsDialogTitle": "Reset all stats",
    "settingsSpecialThanks": "Special thanks:",
    "share": "Share with friends",
    "shareCopy": "Copy link",
    "shareCopySuccess": "Link copied!",
    "shareGamesMenu": "Discover games",
    "shareHeadline": "Introducing a new way to play",
    "shareLink": "http://microsoft.com/edge/surf",
    "shareMessage": "Did you know you can play the surf game and other great games from the games menu in the Microsoft Edge sidebar?",
    "shareMobile": "Share",
    "textdirection": "ltr",
    "themeBikeTitle": "Let's bike",
    "themeHorizonTitle": "Let's surf",
    "themeMenuSubtitle": "Theme $1 of $2",
    "themeSkiTitle": "Let's ski",
    "themeSurfTitle": "Surf classic"
};
